<?php
/**
 * Coyô Software
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contato@coyo.com.br so we can send you a copy immediately.

 * @package     CoyoSoftware_Oneview
 * @author      Coyô Software
 * @copyright   Copyright (c) 2014 Coyô Software (http://www.coyo.com.br)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript">
    //<![CDATA[
    function oneview_export() {
        new Ajax.Request('<?php echo $this->getAjaxExportUrl() ?>', {
            method:     'POST',
            onSuccess: function(transport){
	            if (transport.responseText) {
	                alert("Contatos exportados com sucesso!");
	            }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>